# Board Games Preprocessing
---


**Dataset:** [Board Games Database from BoardGameGeek](https://www.kaggle.com/datasets/threnjen/board-games-database-from-boardgamegeek)

This notebook is simply to apply transforms and feature engineering on the datasets to be exported for training. If you would like to see the reasoning behind the cleaning, please checkout eda.ipynb

In [29]:
import kagglehub
import pandas as pd
import numpy as np

In [30]:
path = kagglehub.dataset_download("threnjen/board-games-database-from-boardgamegeek")

games = pd.read_csv(f"{path}/games.csv")
user_ratings = pd.read_csv(f"{path}/user_ratings.csv")
mechanics = pd.read_csv(f"{path}/mechanics.csv")
subcategories = pd.read_csv(f"{path}/subcategories.csv")
artist = pd.read_csv(f"{path}/artists_reduced.csv")
publisher = pd.read_csv(f"{path}/publishers_reduced.csv")

Using Colab cache for faster access to the 'board-games-database-from-boardgamegeek' dataset.

In [31]:
# create predicted average ratings
rating = user_ratings.groupby(by=["BGGId"], dropna=False)["Rating"].mean()
rating = pd.DataFrame(rating.reset_index())
rating = rating.drop(["BGGId"], axis=1)
rating.head()

     Rating
0  7.672014
1  6.642697
2  7.484350
3  6.599476
4  7.439818

In [32]:
# drop unwanted columns and sort by id

artist = artist.sort_values(by=['BGGId'])
publisher = publisher.sort_values(by=['BGGId'])
subcat = subcategories.sort_values(by=['BGGId'])
games = games.sort_values(by=['BGGId'])

artist = artist.drop(["BGGId"], axis=1)
publisher = publisher.drop(["BGGId"], axis=1)
subcat = subcat.drop(["BGGId"], axis=1)
games = games.drop(["BGGId", "Family", "ComAgeRec", "LanguageEase", "Description", "ImagePath", "Name",
                    "Rank:boardgame", "Rank:strategygames", "Rank:abstracts",
                    "Rank:familygames", "Rank:thematic", "Rank:cgs", "Rank:wargames",
                    "Rank:partygames", "Rank:childrensgames",
                    "Cat:Thematic", "Cat:Strategy", "Cat:War", "Cat:Family",
                    "Cat:CGS", "Cat:Abstract", "Cat:Party", "Cat:Childrens"], axis=1)

In [33]:
# combine metadata into one set

df = pd.concat([games, artist, publisher, subcat], axis=1)
df.head()

,YearPublished,GameWeight,AvgRating,BayesAvgRating,StdDev,MinPlayers,MaxPlayers,BestPlayers,GoodPlayers,NumOwned,...,Exploration,Miniatures,Territory Building,Card Game,Educational,Puzzle,Collectible Components,Word Game,Print & Play,Electronic
0,1986,4.3206,7.61428,7.10363,1.57979,3,5,5,"['4', '5']",7498,...,0,0,0,0,0,0,0,0,0,0
1,1981,1.9630,6.64537,5.78447,1.45440,3,4,0,[],1285,...,0,0,0,1,0,0,0,0,0,0
2,1998,2.4859,7.45601,7.23994,1.18227,2,4,3,"['2', '3', '4']",15578,...,0,0,0,0,0,0,0,0,0,0
3,1992,2.6667,6.60006,5.67954,1.23129,2,4,0,[],638,...,0,0,0,0,0,0,0,0,0,0
4,1964,2.5031,7.33861,7.14189,1.33583,2,6,4,"['3', '4', '5']",23735,...,0,0,1,0,0,0,0,0,0,0

Saving locally or through vm

In [35]:
%store rating df

Stored 'rating' (DataFrame)
Stored 'df' (DataFrame)

In [38]:
# df.to_csv("df.csv")
# rating.to_csv("ratings.csv")